### ISSUE TITLE
QuestStorage issue

### ISSUE THREAD

**Issue by feliperodalves** [gordonbay/capernia-ots-datapack#6] opened 2016-05-09 15:02 UTC
Ainda estou em fase de aprendizado e não sei exatamente onde possa estar o erro...
Ao acessar farmine pelo tapete, não é possível validar o queststorage e abrir as portas necessárias para voltar.
O real problema é que a distro foi feita para "pular" as quests, porém este evento procura no queststorage do personagem para validação.
obs. alguns npc's desta mesma quest também ficam problematicos

**Comment by gordonbay** [comment] 2016-05-09 16:06
I ll look into it.

**Comment by gordonbay** [comment] 2016-05-09 21:13
Can you be more specific? Exact coordination, exact NPC, exact doors, exact quest phase, exact mission.
And please check if it wasn't fixed by today's update cause there was core NPC missing before it, Lazaran, Curos, Ztiss and Melfar were nonexistent on original Mitsuig datapack.

**Comment by zReeke** [comment] 2016-05-09 21:25
Is not a bug on the quest storage its a bug in the carpet NPC that took you to farmine carpet without having the storage to travel there, once you have all storage/quest finished tote point you can use the magic carpet and snake teleport you are able to use the door, and the other one you need to ask for the quest in order to go walking there unfortunately I'm sure that at the moment you can;t finish the quest because it has missing npc, etc etc etc

**Comment by gordonbay** [comment] 2016-05-09 21:41
I just made some tests and the NPC Melian does not check The New Frontier Quest storage for completion in order to allow his services.

**Comment by zReeke** [comment] 2016-05-09 21:48
when I first try to test the quest i got stuck in the second mission I couldn't find NPC Melfar and i just quit testing haha so im not sure what happens after mission 2 but mission 1 does work try adding into the spawn

**Comment by gordonbay** [comment] 2016-05-13 02:55
This issue report is not respecting the [rules on issue post](https://github.com/gordonbay/capernia-ots-datapack/wiki/Issues) and if the author dont change it on the next 5 days it will be closed.

**Comment by gordonbay** [comment] 2016-05-20 19:25
No response, closed.

**Closed by gordonbay** 2016-05-20 19:25 UTC
